// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef weather_h
#define weather_h
#include <FL/Fl.H>
double f2c(double f);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *Window;
#include <FL/Fl_Input.H>
extern Fl_Input *input2;
#include <FL/Fl_Button.H>
extern Fl_Button *calculate;
#include <FL/Fl_Box.H>
extern Fl_Box *snow;
extern Fl_Box *rain;
extern Fl_Box *cloudy;
extern Fl_Box *clear;
#include <FL/Fl_Output.H>
extern Fl_Output *weather;
extern Fl_Output *temperature;
extern Fl_Output *humidity;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *farenheit;
extern Fl_Round_Button *celsius;
extern Fl_Output *hight;
extern Fl_Output *lowt;
extern Fl_Output *sm;
#endif
